--PARA BUSCAR SABIENDO LOS TIPOS DE DATOS QUE SE QUIERE RECUPERAR , TIPO ENUMERACION, CRITERIO CONCRETO.
SELECT * FROM usuario WHERE name IN ('Maria');
SELECT * FROM usuario WHERE name IN ('Maria','Angela');
