/* LOS INDICES SE USAN PARA ACELERAR LA BUSQUEDA DE LOS REGISTROS,
MEJORA EL RENDIMIENTO.


HAY INDICES PRIMARIOS(PRIMARY INDEX), RELACIONADOS CON PK.
INDICES UNICOS(UNIQUE INDEX) ASEGURA QUE DOS FILAS DE LA TABLA NO TENGA VALORES DUPLICADOS.
INDICES COMPUESTOS (COMPOSITE INDEX ) PERMITE JUNTAR VARIAS COLUMNAS EN UNA SOLA BUSQUEDA UNICA DE INDICE.

CREAR INDICES HACE QUE LA TABLA PESE MAS.
CUANDO SE ESCRIBEN DATOS EN TABLAS INDEXADAS ES MAS LENTO, ESCRIBE EL DATO Y TIENE QUE REGENERAR EL INDICE.
*/

SELECT * FROM users;

--IMAGINAMOS QUE NUESTRA APP SOLO PERMITE HACER BUSQUEDAS POR NOMBRE, LO INTERESANTE ES HACER
--ENTONCES UN INDICE EN EL CAMPO NOMBRES.

CREATE INDEX idx_name
ON users(name);

/*
PARA HACER INDICES UNICOS
CREATE UNIQUE  INDEX idx_name
ON users(name);
*/

CREATE INDEX idx_name_surname
ON users(name,surname);

DROP INDEX idx_name
ON users;
